<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Q_Garage</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Fonts\Smack Laideth Down 2024.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Repository\" />
    <Folder Include="Models\" />
    <Folder Include="UI\Components\" />
    <Folder Include="UI\Inv_Refacc\" />
    <Folder Include="UI\Clie_Autos\" />
    <Folder Include="UI\Finanzas\" />
    <Folder Include="UI\Configuracion\" />
    <Folder Include="UI\Personal\" />
    <Folder Include="UI\Proveedores\" />
    <Folder Include="UI\Taller\" />
    <Folder Include="Utils\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>